<?php

return [
    [
        'slug' => 'building-a-modern-publishing-platform-beyond-wordpress',
        'title' => 'Building a Modern Publishing Platform Beyond WordPress',
        'description' => 'How Razbudise separates editorial decisions, authoritative Laravel workflows, and draft-only Next.js delivery without overstating its active-development status.',
        'published_at' => '2026-07-27',
        'modified_at' => '2026-07-27',
        'reading_time' => 10,
        'category' => 'Publishing Platforms',
        'keywords' => ['Razbudise', 'Laravel', 'Next.js', 'publishing architecture'],
        'related_slugs' => ['designing-editorial-workflows-with-explicit-state-and-ownership', 'migrating-wordpress-content-safely-into-laravel-and-nextjs', 'modernizing-legacy-php-systems-without-breaking-production'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/razbudise-modern-publishing-platform.md')),
    ],
    [
        'slug' => 'designing-editorial-workflows-with-explicit-state-and-ownership',
        'title' => 'Designing Editorial Workflows with Explicit State and Ownership',
        'description' => 'Practical Razbudise lessons on decisions, assignments, ownership, approval, rejection, traceability, conflicts, and human-controlled delivery.',
        'published_at' => '2026-07-26',
        'modified_at' => '2026-07-26',
        'reading_time' => 10,
        'category' => 'Workflow Design',
        'keywords' => ['Razbudise', 'editorial workflow', 'state transitions', 'authorization'],
        'related_slugs' => ['building-a-modern-publishing-platform-beyond-wordpress', 'migrating-wordpress-content-safely-into-laravel-and-nextjs', 'what-building-buildiq-taught-me-about-python-fastapi-and-product-engineering'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/razbudise-editorial-workflows.md')),
    ],
    [
        'slug' => 'migrating-wordpress-content-safely-into-laravel-and-nextjs',
        'title' => 'Migrating WordPress Content Safely into Laravel and Next.js',
        'description' => 'A draft-first migration approach built around source identity, normalization, sanitization, retry safety, review checkpoints, and reversible cutover decisions.',
        'published_at' => '2026-07-25',
        'modified_at' => '2026-07-25',
        'reading_time' => 10,
        'category' => 'Content Migration',
        'keywords' => ['WordPress', 'Laravel', 'Next.js', 'content migration'],
        'related_slugs' => ['building-a-modern-publishing-platform-beyond-wordpress', 'designing-editorial-workflows-with-explicit-state-and-ownership', 'safe-production-deployments-for-laravel-and-legacy-php'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/razbudise-wordpress-migration.md')),
    ],
    [
        'slug' => 'what-building-buildiq-taught-me-about-python-fastapi-and-product-engineering',
        'title' => 'What Building BuildIQ Taught Me About Python, FastAPI, and Product Engineering',
        'description' => 'Practical lessons from building BuildIQ with Python, FastAPI, PostgreSQL, React, and TypeScript while retaining a strong PHP and Laravel foundation.',
        'published_at' => '2026-07-13',
        'modified_at' => '2026-07-13',
        'reading_time' => 9,
        'category' => 'Product Engineering',
        'keywords' => ['Python', 'FastAPI', 'product engineering', 'BuildIQ'],
        'related_slugs' => ['safe-production-deployments-for-laravel-and-legacy-php', 'modernizing-legacy-php-systems-without-breaking-production'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/buildiq-python-fastapi-product-engineering.md')),
    ],
    [
        'slug' => 'modernizing-legacy-php-systems-without-breaking-production',
        'title' => 'Modernizing Legacy PHP Systems Without Breaking Production',
        'description' => 'A practical, confidentiality-aware approach to improving legacy PHP systems through workflow discovery, controlled change, security, and rollback planning.',
        'published_at' => '2026-07-12',
        'modified_at' => '2026-07-13',
        'reading_time' => 9,
        'category' => 'Legacy Modernization',
        'keywords' => ['PHP', 'legacy modernization', 'production safety'],
        'related_slugs' => ['safe-production-deployments-for-laravel-and-legacy-php', 'what-building-buildiq-taught-me-about-python-fastapi-and-product-engineering'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/modernizing-legacy-php-systems.md')),
    ],
    [
        'slug' => 'safe-production-deployments-for-laravel-and-legacy-php',
        'title' => 'How I Approach Safe Production Deployments for Laravel and Legacy PHP',
        'description' => 'A production deployment method built around exact commits, runtime checks, protected configuration, reversible releases, verification, and clean handoff.',
        'published_at' => '2026-07-11',
        'modified_at' => '2026-07-13',
        'reading_time' => 9,
        'category' => 'Production Operations',
        'keywords' => ['Laravel', 'PHP', 'deployment', 'production operations'],
        'related_slugs' => ['modernizing-legacy-php-systems-without-breaking-production', 'what-building-buildiq-taught-me-about-python-fastapi-and-product-engineering'],
        'status' => 'published',
        'body' => file_get_contents(resource_path('content/articles/safe-production-deployments.md')),
    ],
    [
        'slug' => 'engineering-notes-draft',
        'title' => 'Engineering notes draft',
        'description' => 'Unpublished layout fixture.',
        'published_at' => null,
        'modified_at' => null,
        'reading_time' => null,
        'category' => null,
        'keywords' => [],
        'related_slugs' => [],
        'status' => 'draft',
        'body' => 'This draft is not published.',
    ],
];
