<?php

return [
    'name' => 'Aleksandar Dimovski',
    'email' => env('PORTFOLIO_EMAIL', 'aleksandar.dimovski@me.com'),
    'phone' => '+389 75 458 790',
    'github' => 'https://github.com/gunnero',
    'location' => 'Bitola 7000, North Macedonia',
    'projects' => [
        ['slug' => 'buildiq', 'name' => 'BuildIQ', 'eyebrow' => 'AI-assisted construction management', 'summary' => 'An AI-assisted construction management platform in active development, built with Python, FastAPI, React, TypeScript, and PostgreSQL around deterministic business workflows.', 'context' => 'Current product-development work translating construction and business workflows into a maintainable software platform while keeping future assistance bounded and human-accountable.', 'problem' => 'Complex workflows require explicit permissions, subscription states, deterministic calculations, production configuration, and dependable release gates.', 'role' => 'Founder, Backend & Product Engineer', 'responsibilities' => ['Product planning and architecture documentation', 'Python and FastAPI backend delivery', 'React and TypeScript product interface', 'Role, permission, and subscription-state enforcement', 'Production configuration gates, CI, dependency auditing, and security testing'], 'approach' => 'Model domain boundaries explicitly, keep authoritative calculations and business rules on the backend, enforce access and subscription state server-side, and ship reviewable increments backed by tests and release documentation.', 'technology' => ['Python', 'FastAPI', 'Starlette', 'PostgreSQL', 'React', 'TypeScript', 'Vite', 'Vitest'], 'challenges' => 'Maintaining clear authorization, tenant boundaries, deterministic business behavior, and production readiness across a broad active product surface.', 'security' => 'Authorization, role enforcement, subscription state, tenant isolation, production configuration, dependency auditing, Gitleaks, and security tests are release requirements. Private implementation details remain excluded.', 'outcome' => 'An active, testable product foundation with 127 backend tests, 45 frontend tests, CI, architecture documentation, and release evidence; no customer, revenue, adoption, or commercial-traction claim is made.', 'lessons' => 'Product planning, domain language, enforcement boundaries, testing, and operational gates must evolve together. AI assistance must remain bounded by authorization, review, and deterministic product rules.', 'repository' => 'https://github.com/gunnero/BuildIQ', 'confidential' => false, 'featured' => true],
        ['slug' => 'mediahub', 'name' => 'MediaHub', 'eyebrow' => 'Movie and television tracking', 'summary' => 'A responsive movie and television tracking platform in active development across backend, frontend, importer, social privacy, and testing work.', 'context' => 'A poster-led product for tracking viewing activity, discovering content, and using existing library data to support personal recommendations.', 'problem' => 'Viewing state, discovery, diary history, collections, and social features need to remain coherent across devices and incomplete external metadata.', 'role' => 'Founder and Product Engineer', 'responsibilities' => ['Continue Watching and Mark finished workflows', 'Recommendations from existing data and recently added content', 'Upcoming releases, diary, friends, collections, and statistics', 'Privacy-safe social content and responsive states', 'Backend, frontend, importer, and testing work'], 'approach' => 'Use explicit viewing states, bounded importer behavior, responsive product states, and privacy-aware social boundaries backed by automated checks.', 'technology' => ['PHP', 'Laravel', 'JavaScript', 'External metadata APIs'], 'challenges' => 'External metadata can be incomplete while viewing history, recommendations, and social visibility must remain predictable.', 'security' => 'Social content is privacy-aware; credentials, private catalog data, and non-public infrastructure remain outside this case study.', 'outcome' => 'An actively developed product surface covering tracking, discovery, diary, collections, social features, and statistics; no public launch or adoption is claimed.', 'lessons' => 'Media products need explicit state transitions, safe importers, and privacy rules that are visible in the user experience.', 'repository' => 'https://github.com/gunnero/mediahub', 'confidential' => false, 'featured' => true],
        ['slug' => 'hera-backoffice', 'name' => 'Hera Backoffice', 'eyebrow' => 'Sanitized client case study', 'summary' => 'Modernization and maintenance of a production legacy PHP business administration platform.', 'context' => 'An established business system requiring careful ongoing development while remaining operational.', 'problem' => 'Legacy workflows needed stabilization, clearer maintenance paths, and safer releases.', 'role' => 'Senior PHP Developer', 'responsibilities' => ['Legacy-system analysis', 'Workflow stabilization', 'Maintainability and security improvements', 'Git-based deployment and documentation'], 'approach' => 'Make narrow, reversible improvements backed by regression checks and production-aware release procedures.', 'technology' => ['PHP', 'MySQL', 'JavaScript', 'Linux', 'Git'], 'challenges' => 'Improving a live legacy system without disrupting business-critical workflows.', 'security' => 'Sanitized case study. Client information, production URLs, source code, data, and business rules are confidential.', 'outcome' => 'A safer maintenance and release practice with incremental improvements to the existing platform.', 'lessons' => 'Legacy modernization succeeds through disciplined understanding and controlled change.', 'repository' => null, 'confidential' => true, 'featured' => true],
        ['slug' => 'nema30-backoffice', 'name' => 'Nema30 Backoffice', 'eyebrow' => 'Sanitized client case study', 'summary' => 'PHP business backoffice modernization across documents, operations, compatibility, and production support.', 'context' => 'An existing operational application evolving alongside business and infrastructure needs.', 'problem' => 'Document generation, workflows, deployment migration, and database compatibility required incremental improvement.', 'role' => 'Senior PHP Developer', 'responsibilities' => ['Document workflows', 'Deployment migration', 'Database compatibility', 'Production support'], 'approach' => 'Preserve existing behavior while isolating risk and improving one operational boundary at a time.', 'technology' => ['PHP', 'MySQL', 'HTML/CSS', 'Linux', 'Git'], 'challenges' => 'Maintaining continuity while modernizing an application with established workflows.', 'security' => 'Sanitized case study. No customer data, production details, private code, or confidential business rules are shown.', 'outcome' => 'Incremental modernization with production continuity kept central to delivery.', 'lessons' => 'Operational software rewards compatibility, observability, and careful release design.', 'repository' => null, 'confidential' => true, 'featured' => false],
        ['slug' => 'razbudise', 'name' => 'Razbudise', 'eyebrow' => 'Digital publishing and editorial workflow', 'summary' => 'A digital publishing and editorial workflow platform in active development with traceable decisions and draft-only delivery.', 'context' => 'A publishing product moving from legacy content toward a structured editorial operating flow and application platform.', 'problem' => 'Conversation decisions, approvals, rejections, assignments, and delivery need explicit traceability without overstating automated publication.', 'role' => 'Founder, Product Engineer, and Backend Engineer', 'responsibilities' => ['Editorial operating flow', 'Conversation decisions, approval, and rejection', 'Assignment traceability and draft-only delivery', 'Command-line delivery tooling', 'Testing and documentation'], 'approach' => 'Model editorial decisions and assignment state explicitly, keep delivery draft-only, and validate command-line and API paths with documented acceptance rules.', 'technology' => ['PHP', 'Laravel', 'REST API', 'Next.js'], 'challenges' => 'Preserving content integrity and decision history while evolving editorial workflows and migration tooling.', 'security' => 'Unpublished content, private operational details, internal endpoints, and publication volume are not disclosed.', 'outcome' => 'A testable editorial and delivery foundation in active development; no automated publication volume is claimed.', 'lessons' => 'Editorial systems require explicit decisions, ownership, traceability, and safe delivery states.', 'repository' => null, 'confidential' => true, 'featured' => false],
        ['slug' => 'kalveri', 'name' => 'Kalveri', 'eyebrow' => 'Software company and product ecosystem', 'summary' => 'An evolving software company and product ecosystem shaped around practical business tools.', 'context' => 'Active product-development work spanning company foundations, product direction, and the systems needed to support future software products.', 'problem' => 'Early product work needs enough technical structure to support exploration without presenting unreleased plans as finished products.', 'role' => 'Founder and Product Engineer', 'responsibilities' => ['Product planning', 'Technical foundations', 'Application development', 'Operational setup'], 'approach' => 'Develop the ecosystem incrementally, keeping product claims bounded to work that can be shown honestly.', 'technology' => ['PHP', 'Laravel', 'JavaScript', 'Linux'], 'challenges' => 'Building reusable foundations while product directions are still being validated.', 'security' => 'Unreleased plans, private repositories, production details, and commercial information are intentionally excluded.', 'outcome' => 'Active development of a company and product foundation; no commercial success or public adoption is claimed.', 'lessons' => 'Early product ecosystems benefit from clear boundaries between present capabilities and future direction.', 'repository' => null, 'confidential' => true, 'featured' => false],
    ],
    'articles' => [
        ['slug' => 'modernizing-legacy-php-systems-without-breaking-production', 'title' => 'Modernizing Legacy PHP Systems Without Breaking Production', 'description' => 'A practical approach to improving business-critical PHP systems through understanding, backups, Git, small changes, testing, security, and documentation.', 'published_at' => '2026-07-12', 'reading_time' => 7, 'status' => 'published', 'body' => <<<'MD'
Legacy modernization starts with restraint. Before I change code, I need to understand which workflows keep the business moving, who depends on them, and what failure would look like. A technically awkward process can still be operationally critical.

## Understand the workflow before the framework

I begin by tracing the real path through the system: inputs, decisions, generated documents, database changes, integrations, and the people responsible for each step. I document what the application actually does instead of assuming what it was intended to do.

That context matters more than choosing a new framework. A rewrite made without evidence can remove years of accumulated business knowledge along with the technical debt.

## Build a rollback path first

Every production change needs a credible way back. That means verified backups, a copy of the relevant configuration, and a release procedure that identifies exactly what changed. A backup is only useful when its location, contents, and restoration path are understood.

## Move change into Git

Older PHP systems often predate a consistent version-control and deployment process. Bringing the work into Git creates a reviewable history and makes releases reproducible. I keep production configuration and credentials outside the repository, isolate environment-specific files, and make the deployed commit easy to identify.

## Prefer small, observable changes

I avoid broad rewrites unless the evidence justifies them. A narrow change is easier to review, test, release, and reverse. It also makes it clearer whether the change solved the intended problem.

For systems such as Hera Backoffice and Nema30 Backoffice, this means incremental modernization: stabilize a workflow, improve maintainability or security, document it, and release it carefully. The private code and business rules remain confidential; the engineering discipline is transferable.

## Test before deployment

Automated tests are valuable, but legacy systems may not begin with broad coverage. I combine focused regression tests with syntax checks, configuration validation, database compatibility checks, and a production-oriented smoke plan. The verification should reflect the workflow being changed, not only whether a page returns HTTP 200.

## Treat the server as part of the system

PHP versions, extensions, Apache or Nginx configuration, PHP-FPM, permissions, scheduled work, certificates, logs, and deployment ownership can all affect an otherwise correct application change. I verify the target runtime and run application commands as the owning site user. Configuration changes get validated before services reload.

## Security and documentation are modernization work

Modernization includes removing exposed secrets, tightening permissions, validating inputs, reviewing authorization, protecting private files, and making errors safe for production. Documentation should record requirements, deployment steps, rollback, and the reasons behind important constraints.

## The practical lesson

Reliable modernization is not a dramatic replacement. It is a sequence of informed, reversible improvements. Understand the business workflow, protect the recovery path, use Git, change one boundary at a time, verify on the real runtime, and leave the system easier for the next engineer to understand.
MD],
        ['slug' => 'engineering-notes-draft', 'title' => 'Engineering notes draft', 'description' => 'Unpublished layout fixture.', 'published_at' => null, 'reading_time' => null, 'status' => 'draft', 'body' => 'This draft is not published.'],
    ],
];
