<?php

return [
    'name' => 'Aleksandar Dimovski',
    'email' => env('PORTFOLIO_EMAIL', 'hello@aleksandardimovski.me'),
    'github' => 'https://github.com/gunnero',
    'location' => 'Skopje, North Macedonia',
    'projects' => [
        ['slug' => 'buildiq', 'name' => 'BuildIQ', 'eyebrow' => 'Product engineering', 'summary' => 'A business software product shaped from domain workflows into a maintainable Laravel platform.', 'context' => 'A product-led system for turning complex operational work into clear, structured software.', 'problem' => 'Business processes needed a dependable digital model without adding unnecessary complexity.', 'role' => 'Product Engineer and Senior Laravel Engineer', 'responsibilities' => ['Product and domain modelling', 'Backend architecture', 'Secure multi-tenant workflows', 'Release quality'], 'approach' => 'Translate real workflows into explicit application boundaries, then ship in small, testable increments.', 'technology' => ['PHP', 'Laravel', 'PostgreSQL', 'TypeScript'], 'challenges' => 'Balancing a broad product surface with clear ownership, isolation, and maintainability.', 'security' => 'Tenant isolation and authorization are treated as architectural concerns. No private implementation details are disclosed.', 'outcome' => 'A coherent product foundation designed for continued, incremental delivery.', 'lessons' => 'Good product engineering connects domain language, system boundaries, and operational reality.', 'repository' => null, 'confidential' => true, 'featured' => true],
        ['slug' => 'mediahub', 'name' => 'MediaHub', 'eyebrow' => 'Media operations', 'summary' => 'A poster-led media operations dashboard for reviewing metadata and managing content workflows.', 'context' => 'Internal tooling for navigating a growing media catalog and its operational states.', 'problem' => 'Metadata review and exception handling needed a clearer, safer workflow.', 'role' => 'Product Engineer', 'responsibilities' => ['Workflow design', 'Backend services', 'Metadata review UX', 'Operational safeguards'], 'approach' => 'Use task-oriented views and explicit queues to make exceptions visible and recoverable.', 'technology' => ['PHP', 'Laravel', 'Blade', 'External APIs'], 'challenges' => 'External metadata can be incomplete or inconsistent and must fail safely.', 'security' => 'Third-party credentials and private catalog data remain outside this case study.', 'outcome' => 'A focused operational interface that keeps review work understandable.', 'lessons' => 'Reliable integrations need visible failure states and bounded retry behavior.', 'repository' => null, 'confidential' => true, 'featured' => true],
        ['slug' => 'hera-backoffice', 'name' => 'Hera Backoffice', 'eyebrow' => 'Sanitized client case study', 'summary' => 'Modernization and maintenance of a production legacy PHP business administration platform.', 'context' => 'An established business system requiring careful ongoing development while remaining operational.', 'problem' => 'Legacy workflows needed stabilization, clearer maintenance paths, and safer releases.', 'role' => 'Senior PHP Developer', 'responsibilities' => ['Legacy-system analysis', 'Workflow stabilization', 'Maintainability and security improvements', 'Git-based deployment and documentation'], 'approach' => 'Make narrow, reversible improvements backed by regression checks and production-aware release procedures.', 'technology' => ['PHP', 'MySQL', 'JavaScript', 'Linux', 'Git'], 'challenges' => 'Improving a live legacy system without disrupting business-critical workflows.', 'security' => 'Sanitized case study. Client information, production URLs, source code, data, and business rules are confidential.', 'outcome' => 'A safer maintenance and release practice with incremental improvements to the existing platform.', 'lessons' => 'Legacy modernization succeeds through disciplined understanding and controlled change.', 'repository' => null, 'confidential' => true, 'featured' => true],
        ['slug' => 'nema30-backoffice', 'name' => 'Nema30 Backoffice', 'eyebrow' => 'Sanitized client case study', 'summary' => 'PHP business backoffice modernization across documents, operations, compatibility, and production support.', 'context' => 'An existing operational application evolving alongside business and infrastructure needs.', 'problem' => 'Document generation, workflows, deployment migration, and database compatibility required incremental improvement.', 'role' => 'Senior PHP Developer', 'responsibilities' => ['Document workflows', 'Deployment migration', 'Database compatibility', 'Production support'], 'approach' => 'Preserve existing behavior while isolating risk and improving one operational boundary at a time.', 'technology' => ['PHP', 'MySQL', 'HTML/CSS', 'Linux', 'Git'], 'challenges' => 'Maintaining continuity while modernizing an application with established workflows.', 'security' => 'Sanitized case study. No customer data, production details, private code, or confidential business rules are shown.', 'outcome' => 'Incremental modernization with production continuity kept central to delivery.', 'lessons' => 'Operational software rewards compatibility, observability, and careful release design.', 'repository' => null, 'confidential' => true, 'featured' => false],
        ['slug' => 'razbudise', 'name' => 'Razbudise', 'eyebrow' => 'Digital publishing', 'summary' => 'An API-first publishing platform and content migration foundation.', 'context' => 'A publishing product moving from legacy content toward a structured application platform.', 'problem' => 'Existing content and editorial workflows needed a stable modern foundation.', 'role' => 'Product and Backend Engineer', 'responsibilities' => ['API design', 'Content modelling', 'Migration tooling', 'Launch quality'], 'approach' => 'Build a clear content model first, then validate migration and publishing paths end to end.', 'technology' => ['PHP', 'Laravel', 'REST API', 'Next.js'], 'challenges' => 'Preserving content integrity while changing the underlying platform.', 'security' => 'Private operational details and unpublished content are not disclosed.', 'outcome' => 'A testable foundation for migration and continued product development.', 'lessons' => 'Migration quality depends on explicit acceptance rules, not only successful imports.', 'repository' => null, 'confidential' => true, 'featured' => false],
        ['slug' => 'kalveri', 'name' => 'Kalveri', 'eyebrow' => 'Software company and product ecosystem', 'summary' => 'An evolving software company and product ecosystem shaped around practical business tools.', 'context' => 'Active product-development work spanning company foundations, product direction, and the systems needed to support future software products.', 'problem' => 'Early product work needs enough technical structure to support exploration without presenting unreleased plans as finished products.', 'role' => 'Founder and Product Engineer', 'responsibilities' => ['Product planning', 'Technical foundations', 'Application development', 'Operational setup'], 'approach' => 'Develop the ecosystem incrementally, keeping product claims bounded to work that can be shown honestly.', 'technology' => ['PHP', 'Laravel', 'JavaScript', 'Linux'], 'challenges' => 'Building reusable foundations while product directions are still being validated.', 'security' => 'Unreleased plans, private repositories, production details, and commercial information are intentionally excluded.', 'outcome' => 'Active development of a company and product foundation; no commercial success or public adoption is claimed.', 'lessons' => 'Early product ecosystems benefit from clear boundaries between present capabilities and future direction.', 'repository' => null, 'confidential' => true, 'featured' => false],
    ],
    'articles' => [
        ['slug' => 'engineering-notes-coming-soon', 'title' => 'Engineering notes are coming soon', 'description' => 'A placeholder for future articles based on real project experience.', 'published_at' => null, 'reading_time' => null, 'status' => 'draft', 'body' => 'This draft is not published.'],
    ],
];
