<?php

return [
    'buildiq' => [
        'executive_summary' => 'BuildIQ is the flagship product-engineering case study: a construction management platform in active development, built with Python, FastAPI, React, TypeScript, and PostgreSQL around deterministic business workflows, explicit authorization, subscription enforcement, production gates, testing, and documentation.',
        'architecture' => ['A Python and FastAPI application core owns business rules, authorization, subscription state, calculations, API boundaries, and protected PDF generation.', 'PostgreSQL persists company-scoped product data behind explicit application services.', 'A React and TypeScript interface consumes documented API contracts; Vite provides production builds and route-level lazy loading while Vitest covers product behavior.', 'AI assistance is a bounded product direction, not a replacement for deterministic workflows or an unsupported implementation claim.'],
        'production' => ['Environment-specific configuration is validated before release.', 'Tenant isolation, role and permission enforcement, subscription state, 127 backend tests, 45 frontend tests, dependency auditing, Gitleaks, and build output form the reviewed release gate.', 'CI, release documentation, architecture evidence, reviewed commits, controlled migrations, health checks, and rollback-ready verification support production safety.'],
        'roadmap' => ['Continue hardening domain boundaries and tenant-scoped workflows.', 'Expand evidence-led product modules only after their rules and acceptance criteria are explicit.', 'Keep AI-assisted capabilities bounded by authorization, review, and observable failure states.'],
        'diagram' => "flowchart LR\n    U[Authenticated user] --> F[React and TypeScript interface]\n    F --> A[FastAPI boundary]\n    A --> P[Authorization and subscription policies]\n    P --> S[Python domain services]\n    S --> D[(PostgreSQL company data)]\n    S --> C[Deterministic calculations and documents]\n    T[Pytest, Vitest, audits, and Gitleaks] --> A\n    G[Production configuration gates] --> A",
    ],
    'mediahub' => [
        'executive_summary' => 'MediaHub is a movie and television tracking product in active development. It connects viewing-state workflows, discovery, diary history, collections, social privacy, external metadata import, responsive interfaces, and automated testing.',
        'architecture' => ['The product UI presents poster-led responsive states for discovery, tracking, diary, collections, and statistics.', 'Backend services own viewing transitions such as Continue Watching and Mark finished.', 'Importer and metadata boundaries isolate incomplete third-party data from stable user-owned state.', 'Privacy rules constrain which social and friend activity can be surfaced.'],
        'production' => ['Importer failures are visible, bounded, and recoverable rather than retried indefinitely.', 'Frontend, backend, importer, privacy, and responsive-state checks are verified together.', 'External credentials and provider-specific failure details remain outside public evidence.'],
        'roadmap' => ['Refine recommendations derived from existing user-owned data.', 'Strengthen diary, friends, collections, upcoming releases, and statistics as coherent product journeys.', 'Continue improving importer observability and privacy-safe social states.'],
        'diagram' => "flowchart LR\n    M[External metadata] --> Q[Importer and review boundary]\n    Q --> C[(Media catalog)]\n    U[User] --> W[Responsive web product]\n    W --> V[Viewing-state services]\n    V --> H[(Diary and history)]\n    C --> R[Recommendations from existing data]\n    H --> R\n    H --> P[Privacy policy boundary]\n    P --> F[Friends and social views]",
    ],
    'hera-backoffice' => [
        'executive_summary' => 'Hera Backoffice demonstrates disciplined modernization of a production legacy PHP business administration system: understand existing behavior, stabilize workflows, move change into Git, improve security and maintainability incrementally, and release with rollback in mind.',
        'architecture' => ['The existing PHP application and database remain the operational core.', 'Modernization introduces explicit Git history, documented release boundaries, focused regression checks, and narrow maintainability improvements.', 'Production configuration, client data, private rules, and internal topology remain deliberately excluded.'],
        'production' => ['Backups and restoration paths are established before changing production behavior.', 'Changes are small, reversible, and checked against the affected workflow.', 'Git-based deployment records the exact release while logs and smoke checks validate the result.'],
        'roadmap' => ['Continue isolating high-risk legacy boundaries behind clearer application seams.', 'Add regression evidence around frequently changed workflows.', 'Improve documentation and security controls without forcing an unsupported rewrite.'],
        'diagram' => "flowchart LR\n    W[Business workflow] --> L[Legacy PHP application]\n    L --> D[(Production database)]\n    G[Git-reviewed change] --> R[Focused regression checks]\n    R --> B[Backup and rollback gate]\n    B --> L\n    L --> O[Logs and smoke verification]",
    ],
    'nema30-backoffice' => [
        'executive_summary' => 'Nema30 Backoffice is a production PHP business administration and compliance system. The engineering work centers on legacy migration, document generation, database compatibility, operational workflows, Git discipline, and safe live updates.',
        'architecture' => ['A server-rendered PHP application coordinates business and compliance workflows.', 'Document generation and database interactions are treated as explicit operational boundaries.', 'Compatibility work separates application improvements from environment-specific deployment concerns.'],
        'production' => ['Repository and branching discipline make releases attributable and reversible.', 'Database compatibility and document output are verified before live changes.', 'Backups, configuration preservation, permissions, service checks, and post-release smoke tests protect continuity.'],
        'roadmap' => ['Continue incremental modernization around document and operational boundaries.', 'Increase focused coverage for database compatibility and public-facing workflows.', 'Keep release automation narrow, observable, and reversible.'],
        'diagram' => "flowchart LR\n    U[Operational user] --> P[PHP business application]\n    P --> W[Workflow services]\n    W --> D[(Compatible database)]\n    W --> G[Document generation]\n    C[Reviewed Git release] --> V[Compatibility and regression checks]\n    V --> P\n    P --> O[Production verification]",
    ],
    'razbudise' => [
        'executive_summary' => 'Razbudise is an editorial workflow and digital publishing platform in active development. Its engineering evidence is the explicit handling of conversation decisions, assignments, approval and rejection, traceability, draft-only delivery, command-line tooling, and documented acceptance rules.',
        'architecture' => ['Editorial conversations produce explicit decisions rather than implicit state.', 'Assignments connect responsibility, content, and decision history.', 'Delivery remains draft-only across API and command-line boundaries until a separate publishing decision exists.', 'Tests and documentation verify state transitions and integration contracts.'],
        'production' => ['Unpublished content and internal endpoints are treated as protected operational data.', 'CLI and API delivery paths share acceptance rules and draft-only safeguards.', 'Migration and integration work is verified for traceability, not presented as publication volume.'],
        'roadmap' => ['Deepen assignment and decision traceability across the editorial operating flow.', 'Extend integration evidence while preserving draft-only delivery boundaries.', 'Keep approval, rejection, and publishing authority explicit as the product evolves.'],
        'diagram' => "stateDiagram-v2\n    [*] --> Conversation\n    Conversation --> Assigned: assignment created\n    Assigned --> InReview: draft submitted\n    InReview --> Assigned: changes requested\n    InReview --> Rejected: rejection recorded\n    InReview --> Approved: approval recorded\n    Approved --> DraftDelivered: API or CLI delivery\n    DraftDelivered --> [*]\n    note right of DraftDelivered: Delivery does not imply publication",
    ],
    'kalveri' => [
        'executive_summary' => 'Kalveri is the company and engineering system behind multiple active software products. This case study describes product direction, shared engineering standards, documentation discipline, security, and production readiness without claiming customers, funding, employees, revenue, or market traction.',
        'architecture' => ['Each product keeps its own domain boundaries, data, release evidence, and confidentiality constraints.', 'Shared standards cover documentation, threat-aware design, testing, environment validation, Git releases, rollback, and production verification.', 'Reusable practices are preferred over premature shared platforms that would couple unrelated products.'],
        'production' => ['A product is not treated as production-ready until runtime compatibility, secrets, permissions, caches, migrations, health checks, logs, and rollback are verified.', 'Release reports identify the exact commit and separate application deployment from shared infrastructure maintenance.', 'Private plans and commercial information remain outside the public portfolio.'],
        'roadmap' => ['Continue developing BuildIQ, MediaHub, Razbudise, and future products through evidence-led milestones.', 'Evolve shared standards only when repeated product needs justify them.', 'Keep product claims aligned with verifiable engineering and release state.'],
        'diagram' => "flowchart TB\n    K[Kalveri engineering standards]\n    K --> B[BuildIQ]\n    K --> M[MediaHub]\n    K --> R[Razbudise]\n    K --> F[Future products]\n    D[Documentation and decisions] --> K\n    S[Security and testing] --> K\n    P[Production and rollback discipline] --> K\n    B --> E[Independent product evidence]\n    M --> E\n    R --> E\n    F --> E",
    ],
];
