<?php

return [
    'summary' => 'Senior PHP / Laravel Engineer and Product Engineer with more than a decade of experience building, modernizing, and operating business software. Experienced in Laravel, custom PHP systems, APIs, SQL databases, Linux infrastructure, production deployment, technical leadership, and AI-assisted product development across international remote teams.',
    'competencies' => ['Senior PHP and Laravel development', 'Legacy PHP modernization', 'Backend architecture and REST APIs', 'SQL Server, MySQL, and MariaDB', 'Linux, Apache, Nginx, and production operations', 'Technical leadership and Head of IT experience', 'Product engineering and documentation', 'AI-assisted software workflows', 'WordPress and WooCommerce as supporting technologies'],
    'experience' => [
        ['company' => 'Kalveri', 'title' => 'Founder & Lead Software Engineer', 'period' => '2026 – Present', 'summary' => 'Building a software company and product ecosystem focused on AI-assisted business software, SaaS platforms, media products, publishing systems, and practical automation.', 'highlights' => ['Product strategy and technical direction', 'Active development of BuildIQ, MediaHub, and Razbudise', 'Documentation-driven engineering, security, and production readiness']],
        ['company' => 'Niipit IVS, Denmark', 'title' => 'Senior PHP Developer / Server Administrator', 'period' => 'December 2016 – Present', 'summary' => 'Remote senior PHP development and infrastructure work across custom PHP systems, selected Laravel applications, legacy business software, APIs, integrations, and production hosting.', 'highlights' => ['Linux administration, Apache, Nginx, deployment, maintenance, and performance optimization', 'Nema30 Backoffice, Hera Backoffice, business systems, enterprise and e-commerce platforms', 'WordPress and WooCommerce where appropriate; technical SEO and international client collaboration']],
        ['company' => 'S/N Insurance Broker AD Bitola', 'title' => 'Head of IT', 'period' => 'November 2018 – January 2025', 'summary' => 'Led IT operations, infrastructure, internal software, integrations, reporting, support, security, backups, and vendor coordination for the primary organization and five additional companies.', 'highlights' => ['Business and reporting platforms; SQL Server and MySQL integrations', 'Data synchronization, insurance-related workflows, and operational automation', 'Linux, server administration, infrastructure, and production support']],
        ['company' => 'NicheStack, Czechia', 'title' => 'Laravel Developer', 'period' => 'November 2020 – June 2022', 'summary' => 'Remote Laravel development covering backend features, internal SEO and marketing automation tooling, API integrations, database work, and production maintenance.', 'highlights' => []],
        ['company' => 'Technology Solutions for Business Automation (TSBA)', 'title' => 'Front-End Developer', 'period' => 'January 2017 – September 2019', 'summary' => 'Front-end and mobile-interface development using HTML, CSS, JavaScript, AngularJS, and Ionic.', 'highlights' => []],
        ['company' => 'Intel Marketing (WEHOO)', 'title' => 'Chief Technology Officer', 'period' => 'February 2013 – November 2016', 'summary' => 'Technical leadership across web development, infrastructure, client implementation, delivery, and project coordination.', 'highlights' => []],
        ['company' => 'The Nova Code', 'title' => 'PHP / Joomla Developer', 'period' => 'November 2012 – February 2013', 'summary' => 'PHP, Joomla, HTML/CSS, e-commerce customization, and website maintenance.', 'highlights' => []],
        ['company' => 'Internet Club Alex', 'title' => 'IT Technician', 'period' => 'August 2008 – November 2012', 'summary' => 'Workstation maintenance, operating-system setup, local networking, troubleshooting, customer support, and gaming-center infrastructure.', 'highlights' => []],
    ],
    'education' => ['institution' => 'IT Academy Alexandria', 'period' => 'September 2009 – June 2010', 'qualification' => 'Web Design and Internet Technologies training, including CIW and Adobe web-design certifications.'],
    'certifications' => ['Search Engine Optimization, 2023', 'Information Systems Security Awareness, 2021–2022', 'Laracasts: Laravel 8 From Scratch, 2021', 'Team Treehouse PHP training: Beginning PHP, Object-Oriented PHP, and Intermediate PHP', 'CIW web design certifications, 2010'],
    'languages' => ['Macedonian' => 'Native', 'English' => 'Professional working proficiency'],
];
