<x-layout title="Resume" description="Resume of Aleksandar Dimovski, Senior PHP / Laravel Engineer and Backend & Product Engineer.">
<div class="resume-toolbar container"><a href="#resume" class="button">View Resume</a><a href="{{ route('resume.download') }}" class="button" download>Download PDF</a><button class="button primary" onclick="window.print()">Print Resume</button></div>
<article id="resume" class="resume resume-final container">
<header><div><p class="eyebrow">Senior PHP / Laravel Engineer</p><p class="resume-secondary-title">Backend & Product Engineer</p><h1>Aleksandar Dimovski</h1><p>{{ config('resume.summary') }}</p></div><address><a href="mailto:{{ config('portfolio.email') }}">{{ config('portfolio.email') }}</a><a href="tel:+38975458790">{{ config('portfolio.phone') }}</a><span>{{ config('portfolio.location') }}</span><a href="{{ config('portfolio.github') }}">github.com/gunnero</a><a href="https://aleksandardimovski.me">aleksandardimovski.me</a></address></header>
<section><h2>Technical competencies</h2><div class="resume-skill-groups">@foreach(config('resume.skill_groups') as $group => $items)<div><h3>{{ $group }}</h3><p>{{ implode(' · ', $items) }}</p></div>@endforeach</div></section>
<section><h2>Current and recent experience</h2>@foreach(array_slice(config('resume.experience'), 0, 4) as $role)<div class="resume-role"><div class="role-heading"><h3>{{ $role['title'] }} · {{ $role['company'] }}</h3><strong>{{ $role['period'] }}</strong></div><p>{{ $role['summary'] }}</p>@if($role['highlights'])<ul>@foreach($role['highlights'] as $item)<li>{{ $item }}</li>@endforeach</ul>@endif</div>@endforeach</section>
<div class="resume-page-break"></div>
<section><h2>Earlier experience</h2>@foreach(array_slice(config('resume.experience'), 4) as $role)<div class="resume-role compact"><div class="role-heading"><h3>{{ $role['title'] }} · {{ $role['company'] }}</h3><strong>{{ $role['period'] }}</strong></div><p>{{ $role['summary'] }}</p></div>@endforeach</section>
<section><h2>Selected projects</h2><div class="resume-projects"><p><strong>BuildIQ</strong> — AI-assisted construction management platform built with Python, FastAPI, React, TypeScript, and PostgreSQL. Designed backend authorization, subscription enforcement, production configuration controls, CI validation, dependency security, and documented release workflows.</p><p><strong>MediaHub</strong> — Movie and television tracking platform in active development.</p><p><strong>Hera Backoffice</strong> — Sanitized legacy PHP modernization and production maintenance.</p><p><strong>Nema30 Backoffice</strong> — Sanitized PHP business administration and compliance backoffice.</p><p><strong>Razbudise</strong> — Digital publishing and editorial workflow platform in active development.</p></div></section>
<section class="resume-details"><div><h2>Education and training</h2><h3>{{ config('resume.education.institution') }}</h3><p><strong>{{ config('resume.education.period') }}</strong><br>{{ config('resume.education.qualification') }}</p><h2>Languages</h2>@foreach(config('resume.languages') as $language => $level)<p><strong>{{ $language }}:</strong> {{ $level }}</p>@endforeach</div><div><h2>Selected certifications</h2><ul>@foreach(config('resume.certifications') as $certificate)<li>{{ $certificate }}</li>@endforeach</ul></div></section>
</article>
</x-layout>
